databases:
  - name: xrp_videos_db
    databaseName: xrp_videos_db
    user: xrp_videos_user
    plan: free

services:
  - type: web
    name: xrp-videos
    env: python
    region: oregon
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: >
      gunicorn xrp_site.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: xrp_videos_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "yourdomain.onrender.com"
